### PR TITLE
Fix order of transformer tests

### PR DESCRIPTION
**Pull request by MichaelA-ops**

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
What is this PR?  Can we just close it or something and convert it to an issue?  Why is this here?

**Comment by cmeiklejohn** [comment]
Did you make an issue to track this since we're closing the PR?

**Comment by MichaelA-ops** [comment]
We already have one #193

**Comment by cmeiklejohn** [comment]
Got it, thanks.

**Pull request closed without merging**
