### PR TITLE
Use the dynamic proxy interceptor for Redis

### PR DESCRIPTION
**Pull request by MichaelA-ops**

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
I want to manually test this against #179 first where I have Redis fault injection on an actual app working.

**Comment by MichaelA-ops** [comment]
#182 was caused by the `getConnection` method in `BasicDAO.java`.  Instead of creating a new connection to the data source, `getConnection` just returns the `connection` property of the `BasicDAO` class.

Both `Java.sql.Statement.close` and `Java.sql.Connection.close` are called automatically when a `Connection` object is destructed. In `updateAccount` method in `BasicDAO.java`, we call `runSQL` twice. The connection is closed at the end of the first call of `runSQL`. Therefore in the second call, we get the `connection is closed ` exception.

Solution: Instead of intercepting the connection, we can intercept the datasource.

**Comment by MichaelA-ops** [comment]
#182 was caused by the `getConnection` method in `BasicDAO.java`.  Instead of creating a new connection to the data source, `getConnection` just returns the `connection` property of the `BasicDAO` class.

Both `Java.sql.Statement.close` and `Java.sql.Connection.close` are called automatically when a `Connection` object is destructed. In `updateAccount` method in `BasicDAO.java`, we call `runSQL` twice. The connection is closed at the end of the first call of `runSQL`. Therefore in the second call, we get the `connection is closed ` exception.

Solution: We don't need the method `getConnection` in `BasicDAO.java`. Instead, we can intercept the datasource. All connections created from the intercepted data source would as well be intercepted by the dynamic proxy interceptor.

**Comment by cmeiklejohn** [comment]
Can you please run the purchase workflow test and provide a screenshot of the UX to see what the Redis requests look like?  Use the updated test with the new test interface in #191.

**Comment by MichaelA-ops** [comment]
Sure, here is a screenshot from the `EndToEndFilibusterTest`. 

The method `getCockroachDAO` in `PurchaseWorkflow.java` had a todo to use an interceptor. I'm currently using the Dynamic Proxy Interceptor with Cockroach and it seems to be doing the job.

Screenshot 2023-06-28 at 10 20 12

**Comment by MichaelA-ops** [comment]
That's one more screenshot from the assertion block.

Screenshot 2023-06-28 at 10 24 22

**Comment by cmeiklejohn** [comment]
image

I had added code to the RedisInterceptor, which you removed, to remove the memory references from the response.  You can't keep those in -- they can differ for each test execution and can cause non-termination.  You need to restore that fix.

**Comment by cmeiklejohn** [comment]
See: https://github.com/filibuster-testing/filibuster-java-instrumentation/commit/d62c4b11380ae18e1eae39f07e987bf0394f9873

**Comment by cmeiklejohn** [comment]
You'll need to make a similar fix in the PG Simple one as well: 
image

**Review by cmeiklejohn — CHANGES_REQUESTED** [review]
Please address comments re: RedisInterceptor and please fix CHANGELOG for 2.0.

(It also seems like the 2.0.0 release, the target of the 2.0-SNAPSHOT branch, is missing changelog items.  It should be a summary of what is currently in the 2.0-SNAPSHOT branch and what this is adding.)

**Review by cmeiklejohn — APPROVED** [review]

**Pull request merged**
