### PR TITLE
2.0 snapshot fix conflicts

### PR DESCRIPTION
**Pull request by MichaelA-ops**

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
please remove any fault injection for databases from purchase workflow, should be GRPC only for paper

**Comment by cmeiklejohn** [comment]
lots of these changes seem weird, did you first update 2.0 to use the latest main?

**Comment by cmeiklejohn** [comment]
This PR is impossible to review because it's got stuff already merged into main/master.

**Comment by cmeiklejohn** [comment]
I think you should be fixing this by merging main into 2.0 and then resolving the conflict in that specific merge commit, not opening a new branch.

**Comment by MichaelA-ops** [comment]
The branch _Snapshot 2.0_ is protected and I don't have permission to push directly to it, hence the new PR

**Comment by cmeiklejohn** [comment]
I removed the branch protection.

**Pull request closed without merging**
