### PR TITLE
When shutting down, remove current instance of Core.

### PR DESCRIPTION
**Pull request by cmeiklejohn**
What do we think?

### CODE REVIEW

**Comment by MichaelA-ops** [comment]
Will the core instance get removed every time the filibusterServer is shutdown? After every test? Wouldn't this cause issues with the test reporting?

**Comment by cmeiklejohn** [comment]
> Will the core instance get removed every time the filibusterServer is shutdown? After every test? Wouldn't this cause issues with the test reporting?

Which reporting?  I'm trying to determine if something breaks because of this?  

And, it's after every @TestWithFilibuster, because start/stop is called before/after in the invocation interceptor.  I call it the same place we invoke the GC and clear out any lingering state.

**Comment by MichaelA-ops** [comment]
I meant reporting to the plugin if you run multiple tests and terminate the core in between. Just checked and the plugin doesn't seem to be affected.

The core is pretty expensive to create though. What is the benefit of removing the instance?

**Comment by cmeiklejohn** [comment]
If you look at the code, we already *are* recreating it for each test.  This just sets it to null in between.

**Comment by cmeiklejohn** [comment]
https://github.com/filibuster-testing/filibuster-java-instrumentation/pull/253/files#diff-89b738657243a8aceb1078d65fc2c6e826597317c7bdb5c4133979584bc9c41dR29

**Comment by cmeiklejohn** [comment]
Merging into 2.1.0 for checks, otherwise the build is timing out without your fixes.

**Comment by cmeiklejohn** [comment]
same WorldTest failures.  ???

**Pull request merged**
