### PR TITLE
Pull request to handle #65

### PR DESCRIPTION
**Pull request by jiujiu1123**

### CODE REVIEW

**Comment by jiujiu1123** [comment]
Don't merge just yet. Will review more when I land :)

**Comment by cmeiklejohn** [comment]
This looks good but I have one minor concern about this:

The plugin for IntelliJ refreshes index.html on change -- this means that, there is a space between when you delete everything in the directory and write the index back where that plugin will render a 404 Not Found because the file isn't there.

Perhaps this should:

- [ ] Write the placeholder out first (index.html, javascript, gif)
- [ ] Remove all of the /tmp/filibuster/filibuster-test-execution-*'s that are no longer used.

**Review by cmeiklejohn — CHANGES_REQUESTED** [review]
Please address comments.

**Comment by jiujiu1123** [comment]
What about this? This way it overwrites the index.html without actually deleting it?

**Review by cmeiklejohn — APPROVED** [review]

**Comment by cmeiklejohn** [comment]
Feel free to merge once the PR passes all checks.

**Comment by cmeiklejohn** [comment]
You can ignore the one sonatype check failure.

**Pull request merged**
